{{- include "cilium.ca.setup" . }}   # CA 변수 확보

{{- if .Values.hubble.tls.server.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hubble.tls.server.existingSecret }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certs.server.crt | quote }}
  tls.key: {{ .Values.tls.certs.server.key | quote }}
  ca.crt:  {{ .commonCA.Cert | b64enc }}      # Helm 이 만든 CA
{{- end }}

{{- if .Values.hubble.relay.tls.client.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hubble.relay.tls.client.existingSecret }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certs.relay.crt | quote }}
  tls.key: {{ .Values.tls.certs.relay.key | quote }}
  ca.crt:  {{ .commonCA.Cert | b64enc }}
{{- end }}